---
# Location where configuration files will be stored.
config_dir: '~'

required_packages:
  - python3-pip
  - python3-dev
  - python3-setuptools
  - python3-venv
  - git
  - libyaml-dev
  - build-essential
