---
- hosts: octoprint
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

  tasks:
    - name: Setup Python
      ansible.builtin.import_tasks: tasks/python.yml

    - name: Setup Octoprint
      ansible.builtin.import_tasks: tasks/octoprint.yml

    - name: Setup HA Proxy
      ansible.builtin.import_tasks: tasks/haproxy.yml
